### ISSUE TITLE
Requesting design review with the video lab

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/bio-ai#6]
During phase 2 feedback for the 2023 projects, management requested that a design review with the video lab be held for project 901103's ML work. As this project seems to parallel many of our existing tools, the video lab and I would like to have a design review to understand the goals of this project, why tooling (such as tator) is being used instead of our internal tools and ML pipelines, and to exchange ideas and insights. 

cc: @kgomes @NancyJS

**Comment by danellecline** [comment]
@hohonuuli 
Let's discuss this in detail when we are all back in January 2024 and after the project kick-off meetings.  I'm closing this issue now because this is best handled as a discussion.
cc: @kgomes @NancyJS  @beroe
